import { createIssue, updateIssue, searchIssues, linkIssues, getIssue } from './jira.js';

function safeLabel(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 200);
}

function text(value) {
  if (Array.isArray(value)) return value.join('\n');
  return String(value || '');
}

function descriptionFor(testCase, sourceKey) {
  const steps = Array.isArray(testCase.steps)
    ? testCase.steps.map((step, index) => {
        if (typeof step === 'string') return `${index + 1}. ${step}`;
        const action = step.action || step.step || '';
        const expected = step.expected || step.expectedResult || '';
        return `${index + 1}. ${action}${expected ? `\n   Expected: ${expected}` : ''}`;
      }).join('\n')
    : text(testCase.steps);

  return [
    `Generated by Qat from ${sourceKey}`,
    '',
    `Case ID: ${testCase.id || 'N/A'}`,
    `Priority: ${testCase.priority || 'N/A'}`,
    `Type: ${testCase.type || 'Manual'}`,
    '',
    'Preconditions:',
    text(testCase.preconditions) || 'None specified',
    '',
    'Steps:',
    steps || 'No steps specified',
    '',
    'Expected result:',
    text(testCase.expectedResult || testCase.expected) || 'See step expectations.',
  ].join('\n');
}

function testLabels(sourceKey, caseId) {
  return ['qat', `qat-source-${safeLabel(sourceKey)}`, `qat-case-${safeLabel(caseId)}`];
}

export function parseStructuredCases(raw) {
  const trimmed = String(raw || '').trim();
  const unfenced = trimmed
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```$/, '');
  const parsed = JSON.parse(unfenced);
  const cases = Array.isArray(parsed) ? parsed : parsed.testCases;
  if (!Array.isArray(cases)) throw new Error('Claude no devolvió un array testCases válido');
  return cases;
}

export async function syncTestCases(cfg, sourceKey, testCases, { dryRun = false } = {}) {
  if (!cfg.xrayEnabled) throw new Error('XRAY_ENABLED=false');
  const source = await getIssue(cfg, sourceKey);
  const projectKey = source.fields?.project?.key || sourceKey.split('-')[0];
  const results = [];

  for (const testCase of testCases) {
    if (!testCase?.id || !testCase?.title) {
      results.push({ id: testCase?.id || 'unknown', action: 'skipped', reason: 'missing id/title' });
      continue;
    }

    const labels = testLabels(sourceKey, testCase.id);
    const fields = {
      project: { key: cfg.xrayProjectKey || projectKey },
      issuetype: { name: cfg.xrayTestIssueType },
      summary: `[${testCase.id}] ${testCase.title}`.slice(0, 255),
      description: descriptionFor(testCase, sourceKey),
      labels,
    };

    if (cfg.xrayTestTypeField) fields[cfg.xrayTestTypeField] = cfg.xrayTestTypeValue;

    if (dryRun) {
      results.push({ id: testCase.id, action: 'dry-run', fields });
      continue;
    }

    const jql = `project = "${cfg.xrayProjectKey || projectKey}" AND issuetype = "${cfg.xrayTestIssueType}" AND labels = "${labels[1]}" AND labels = "${labels[2]}"`;
    const found = await searchIssues(cfg, jql, ['key', 'summary', 'labels']);
    let testKey;
    let action;

    if (found.length) {
      testKey = found[0].key;
      await updateIssue(cfg, testKey, fields);
      action = 'updated';
    } else {
      const created = await createIssue(cfg, fields);
      testKey = created.key;
      action = 'created';
    }

    await linkIssues(cfg, sourceKey, testKey, cfg.xrayLinkType);
    results.push({ id: testCase.id, key: testKey, action });
  }

  return results;
}
